# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: 10.0.0.2

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 10.0.0.3:[5] # worker_ip: [(# processes on gpu) for gpu in available_gpus]
    - 10.0.0.4:[5]
    - 10.0.0.5:[5]
    - 10.0.0.6:[5]
    - 10.0.0.7:[5]
    - 10.0.0.8:[5]
    - 10.0.0.9:[4]
    - 10.0.0.10:[4]
    - 10.0.0.11:[4]
    - 10.0.0.12:[4]
    - 10.0.0.13:[4]

exp_path: $HOME/FedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source $HOME/anaconda3/bin/activate fedscale    
    - export NCCL_SOCKET_IFNAME='enp94s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/FedScale/core/evals # Path of log files
    - job_name: reddit                   # Generate logs under this folder: log_path/job_name/time_stamp
    - task: nlp
    - total_worker: 100                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: blog                     # Dataset: openImg, google_speech, reddit
    - data_dir: $HOME/FedScale/dataset/data/reddit    # Path of the dataset
    - data_map_file: $HOME/FedScale/dataset/data/reddit/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: $HOME/FedScale/dataset/data/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: $HOME/FedScale/dataset/data/device_info/client_behave_trace
    - model: albert-base-v2                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - eval_interval: 30                     # How many rounds to run a testing on the testing set
    - epochs: 5000                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 21                       # Remove clients w/ less than 21 samples
    - num_loaders: 4                        # Dataloaders 
    - local_steps: 30
    - learning_rate: 4e-5
    - min_learning_rate: 1e-5
    - batch_size: 20
    - test_bsz: 20


