name: fedscale
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - gurobi
dependencies:
  - python=3.7
#  - sox=14.4.2=h27f72bc_1013
  - gurobi=9.1.0
  - tensorboard
  - pip=20.0.2
  - pip:
    - torch_optimizer
    - torch
#    - torch_baidu_ctc==0.3.0
    - torchvision  
    - transformers
    - scipy==1.4.1
    - matplotlib==3.1.3
    - tensorboardX==2.1
    - python-levenshtein==0.12.0
    - pandas==1.1.0
    - sox==1.3.7
    - PyYAML
    - grpcio==1.40.0
    - gym
    - jupyter
    - opacus
    - pillow==9
#    - sentencepiece
#    - gdown
#    - pyemd==0.5.1
